language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - WP_VERSION=master
    - WP_VERSION=4.7.2

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [ $CODECLIMATE_REPO_TOKEN ]; then ./vendor/bin/test-reporter; fi;

cache:
  directories:
    - vendor/

notifications:
  email: false